{% set name = "glomap" %}
{% set version = "1.1.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://github.com/colmap/{{ name }}/archive/{{ version }}.tar.gz
    sha256: ceb4359087cc6f0294be34dbcfae7d7f352ecc9c7a2c7e068c6e6f9ad590c907
    patches:
      - colmap-310-compat.patch

build:
  number: 0
  ignore_run_exports_from:
    - libblas
    - libcblas
    - colmap
    - gflags   # [not linux]
    - poselib  # [win]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - cmake
    - make                           # [unix]
    - pkg-config
    - ninja
    - llvm-openmp                    # [osx]
    - libgomp                        # [linux]
  host:
    - eigen
    - libblas
    - libcblas
    - suitesparse
    - ceres-solver
    - libboost-devel
    - glog
    - poselib
    - colmap
    - cgal-cpp
    - freeimage
    - sqlite
    - gflags
    - llvm-openmp                    # [osx]
    - libgomp                        # [linux]

test:
  commands:
    - test -f $PREFIX/bin/glomap  # [unix]
    - if not exist %PREFIX%\\Library\\bin\\glomap.exe exit 1  # [win]

about:
  home: https://github.com/colmap/glomap
  license: BSD-3-Clause
  license_file: LICENSE
  summary: GLOMAP is a general purpose global structure-from-motion pipeline for image-based reconstruction.

extra:
  recipe-maintainers:
    - Tobias-Fischer
